name: dmrpp_tests
channels:
- conda-forge
dependencies:
- netcdf4
- python=3.12
- virtualizarr
- kerchunk
- fastparquet
- jupyterlab
- pip
- pip:
  - virtual-tiff
  - git+https://github.com/pydap/pydap.git
